movie/django/ecommerce/cart/urls.py
from django.urls import path
from cart import views
app_name="cart"

urlpatterns = [
    path('addtocart/<int:p>',views.addtocart,name="addtocart"),
    path('cartview/',views.cart_view,name="cartview"),
    path('cartremove/<int:p>',views.cartremove,name="cartremove"),
    path('cartdelete/<int:p>',views.cartdelete,name="cartdelete"),
    path('orderform/',views.orderform,name="orderform"),
    path('orderview/',views.orderview,name="orderview"),
]

movie/django/ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/', include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/django/ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name="search"

urlpatterns = [
    path('searchproducts/',views.searchproducts,name="searchproducts"),
]

movie/django/ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"

urlpatterns = [
    path('categories/',views.allcategories,name="allcategories"),
    path('products/<int:p>',views.allproducts,name="products"),
    path('detail/<int:p>',views.detail,name="detail"),
    path('reg/',views.reg,name="reg"),
    path('login/',views.user_login,name="login"),
    path('logout/',views.user_logout,name="logout"),
    path('',views.home,name="home"),
]

movie/django/ecommerce/templates/addtocart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid mt-5" style="margin-bottom:100px;">
    <div class="row">
        <h4 class="text-center">SHOPPING CART</h4>
        <div class="col-8 border border-1">
            <table class="table table-bordered"  style="border-color:black;">
                <tr>
                    <th colspan="7">CART ITEMS</th>
                </tr>
                {% for i in cart %}
                <tr>
                    <td><img src="{{i.product.image.url}}" height="150px" width="150px"></td>
                    <td>{{i.product.name}}</td>
                    <td>Product ID:{{i.product.id}}<br>
                    Quantity:{{i.quantity}}<br>
                    Unit Price:{{i.quantity}}*{{i.product.price}}</td>
                    <td>Subtotal:{{i.subtotal}}</td>
                    <td>{% if i.product.stock > 0 %}
                    <a href="{% url 'cart:addtocart' i.product.id %}"><i class="fa-solid fa-plus"></i></a><br>
                    <a href="{% url 'cart:cartremove' i.product.id %}"><i class="fa-solid fa-minus"></i></a><br>
                    <a href="{% url 'cart:cartdelete' i.product.id %}"><i class="fa-solid fa-trash-can"></i></a>
                    {% else %}
                    <a href="{% url 'cart:cartremove' i.product.id %}"><i class="fa-solid fa-minus"></i></a><br>
                    <a href="{% url 'cart:cartdelete' i.product.id %}"><i class="fa-solid fa-trash-can"></i></a>
                    {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <div class="col-4 border border-1">
            <table class="table table-bordered" style="border-color:black;">
                <tr>
                    <th colspan="4">CHECK OUT</th>
                </tr>
                <tr>
                    <td colspan="4">TOTAL AMOUNT:{{total}}</td>
                </tr>
            </table>
            <a class="btn btn-primary" href="{% url 'cart:orderform' %}">PLACE ORDER</a>
            <a class="btn btn-primary" href="{% url 'shop:allcategories' %}" style=position:absolute;margin-left:10px;">CONTINUE SHOPPING</a>
        </div>
    </div>
</div>
{% endblock %}

movie/django/ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'mycss/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Limelight&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
        footer
        {
        background-color:#191f4f;
        width:100%;
        height:50px;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <img src="{% static 'images/logo ecom.jpeg' %}" height="60px" width="100px">
    <a class="navbar-brand fw-bold fst-italic" href="#"><h2>ECOMMERCE</h2></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:logout' %}">LOGOUT</a>
        </li>
          {% if user.is_superuser != True %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:allcategories' %}">HOME</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"><sup>{{count}}</sup></i></a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cart:orderview' %}">YOUR ORDERS</a>
        </li>
          <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            CATEGORIES
          </a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:products' i.id %}">{{i.name}}</a></li>
              {% endfor %}
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:reg' %}">REGISTER</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:login' %}">LOGIN</a>
        </li>
              {% endif %}
        {% endif %}
          </ul>
        </li>
      </ul>
    </div>
      </ul>
      <div class="header-social">
        <i class="fab fa-twitter" style="color:black;"></i>
        <i class="fa-brands fa-facebook-f" style="color:black;"></i>
        <i class="fa-brands fa-pinterest-p" style="color:black;"></i>
      </div>
      <form class="d-flex" method="POST" action="{% url 'search:searchproducts' %}">
          {% csrf_token %}
        <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
{% block content %}

{% endblock %}
    <div class="footer">
    <h3><center>© ECOMMERCE&ensp;Pvt Ltd</center></h3>
    </div>
</body>
</html>

movie/django/ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid mt-1">
    <img src="{% static 'images/banner1.jpg' %}" height="700px" width="100%">
</div>
<div class="container-fluid">
    <h2><center>COLLECTIONS</center></h2>
    <p style="color:black;">In publishing and graphic design, Lorem ipsum (/ˌlɔː.rəm ˈɪp.səm/) is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available. It is also used to temporarily replace text in a process called greeking, which allows designers to consider the form of a webpage or publication, without the meaning of the text influencing the design.</p>
</div>
<div class="container-fluid" style="margin-bottom:100px;">
    <div class="row">
        {% for i in c %}
        <div class="col-sm-4">
            <div class="card" style="width: 18rem;">
  <img src="{{i.image.url}}" height="300px" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <a href="{% url 'shop:products' i.id %}" class="btn btn-primary">MORE DETAILS</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

movie/django/ecommerce/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid mt-6">
    <div class="row border border-1">
<div class="col-4 me-5">
    <img src="{{p.image.url}}" height="400px">
</div>
<div class="col-6 me-4">
    <h2>{{p.name}}</h2>
    <p style="text-align:justify;">{{p.desc}}</p>
    <h3 style="color:black">Price:{{p.price}}</h3>
    <h3 style="color:black">Stock:{{p.stock}}</h3>
    {% if user.is_superuser == True %}

    {% if p.stock > 0 %}
    <h3 class="text-success">IN STOCK</h3>
    <a href="{% url 'admin:index' %}" class="btn  btn-primary" style="width:300px;">ADD STOCK</a>
    {% else %}
    <h3 class="text-danger">OUT OF STOCK</h3>
    <a href="{% url 'admin:index' %}" class="btn  btn-primary" style="width:300px;">ADD STOCK</a>
    {% endif %}


    {% else %}
    {% if p.stock > 0 %}
    <a href="{% url 'cart:addtocart' p.id %}" class="btn btn-primary">ADD TO CART</a>
    {% else %}
    <h3 class="text-danger">OUT OF STOCK</h3>
    {% endif %}

    {% endif %}
</div>
</div>
</div>
{% endblock %}

movie/django/ecommerce/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid mt-1">
    <img src="{% static 'images/banner1.jpg' %}" height="700px" width="100%">
</div>
{% endblock %}

movie/django/ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>LOGIN STUDENTS</h1>
<center>
    <form method="POST">
  {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Username</label>
    <input type="text" class="form-control" name="u">
  </div><br>
  <div class="mb-3">
    <label class="form-label">Password</label>
    <input type="password" class="form-control" name="p">
  </div><br>
      <input type="submit" class="=btn btn-primary">
</form>
</center>
{% endblock %}

movie/django/ecommerce/templates/orderdetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3 style="color:black">{{msg}}</h3>
{% endblock %}

movie/django/ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
    <label class="form-label">PHONE NO</label>
    <input type="number" class="form-control" name="ph">
  </div>
    <div class="mb-3">
    <label class="form-label">ADDRESS</label>
    <input type="text" class="form-control" name="ad">
  </div>
  <div class="mb-3">
    <label class="form-label">ACCNO</label>
    <input type="number" class="form-control" name="ac">
  </div>
    <center>
    <button type="submit" class="btn btn-primary">Submit</button>
    </center>
</form>
{% endblock %}

movie/django/ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<h3 style="color:black; margin-top:10px;">NAME OF THE CUSTOMER:{{user}}</h3></center>
{% for i in cart %}
    <div class="container-fluid" style="width:1100px;">
    <div class="row" style="border:1px solid black;">
        <div class="col-4 me-5" style="margin-bottom:10px; margin-top:10px;" >
    <img src="{{i.product.image.url}}" height="200px" width="300px">
        </div>
        <div class="col-6 me-4" style="margin-bottom:10px;" >
    <h4>PRODUCT NAME:{{i.product.name}}</h4>
    <h4>PRODUCT PRICE:{{i.product.price}}</h4>
    <h4>ADDRESS:{{i.address}}</h4>
    <h4>PHONE:{{i.phone}}</h4>
    <h4>NO OF ITEMS:{{i.no_of_items}}</h4>
    <h4>ORDERED ON:{{i.ordered_date}}</h4>
    <h4>DELIVERY STATUS:{{i.delivery_status}}</h4>
        </div>
    </div>
</div><br>
{% endfor %}
{% endblock %}

movie/django/ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid mt-1">
    <img src="{{c.image.url}}" height="700px" width="100%">
</div>
<div class="container-fluid">
    <h2><center>{{c.name}}</center></h2>
    <p style="color:black;">{{c.desc}}</p>
</div>
<div class="container-fluid" style="margin-bottom:100px;">
    <div class="row">
        {% for i in p %}
        <div class="col-sm-4">
            <div class="card" style="width: 18rem;">
  <img src="{{i.image.url}}" height="300px" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <a href="{% url 'shop:detail' i.id %}" class="btn btn-primary">MORE DETAILS</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

movie/django/ecommerce/templates/reg.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<h1 class="txt-center">REGISTER</h1><br><br>
<form method="POST">
  {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Username</label>
    <input type="text" class="form-control" name="u">
  </div>
  <div class="mb-3">
    <label class="form-label">Password</label>
    <input type="password" class="form-control" name="p">
  </div>
    <div class="mb-3">
    <label class="form-label">Confirm Password</label>
    <input type="password" class="form-control" name="cp">
  </div>
  <div class="mb-3">
    <label class="form-label">Email</label>
    <input type="text" class="form-control" name="e">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</center>
{% endblock %}

movie/django/ecommerce/templates/searchproducts.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center><h2>YOU HAVE SEARCHED FOR {{q}}</h2></center>
<div class="container-fluid" style="margin-bottom:100px;">
    <div class="row">
        {% for i in p %}
        <div class="col-sm-4">
            <div class="card" style="width: 18rem;">
  <img src="{{i.image.url}}" height="300px" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <a href="{% url 'shop:detail' i.id %}" class="btn btn-primary">MORE DETAILS</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}