movie/movie/movie/urls.py
from django.contrib import admin
from django.urls import path,include
from movieapp import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/movie/movieapp/urls.py
from django.contrib import admin
from django.urls import path
from movieapp import views
app_name="movieapp"

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',views.home,name="home"),
    path('',views.HomeView.as_view(),name="home"),
    # path('detail/<int:n>/',views.detail,name="detail"),
    path('detail/<int:pk>/',views.Detail.as_view(),name="detail"),
    # path('update/<int:n>/',views.update,name="update"),
    path('update/<int:pk>/',views.Update.as_view(),name="update"),
    # path('delete/<int:n>/',views.delete,name="delete"),
    path('delete/<int:pk>/',views.Delete.as_view(),name="delete"),
    # path('addmovie/',views.addmovie,name="addmovie"),
    path('addmovie/',views.AddMovie.as_view(),name="addmovie"),
]

movie/movie/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=20)
    desc=models.TextField()
    year=models.IntegerField()
    image=models.ImageField(upload_to='movies',null=True,blank=True)

    def __str__(self):
        return self.name

movie/movie/movieapp/forms.py
from django import forms
from movieapp.models import Movie

class Movieform(forms.ModelForm):
    class Meta:
        model=Movie
        fields="__all__"

movie/movie/movieapp/views.py
from django.shortcuts import render
from movieapp.models import Movie
from movieapp.forms import Movieform
from django.views.generic import ListView,DetailView,UpdateView,CreateView,DeleteView
from django.urls import reverse_lazy

# Create your views here.
# def home(request):
#     m=Movie.objects.all()
#     return render(request,'home.html',{'m':m})

class HomeView(ListView):
    model=Movie
    template_name='home.html'
    context_object_name='m'

# def detail(request,n):
#     m=Movie.objects.get(id=n)
#     return render(request,'detail.html',{'m':m})

class Detail(DetailView):
    model=Movie
    template_name='detail.html'
    context_object_name='m'

# def update(request,n):
#     m=Movie.objects.get(id=n)
#     if(request.method=='POST'):
#         form=Movieform(request.POST,request.FILES,instance=m)
#         if form.is_valid():
#             form.save()
#             return home(request)
#
#
#
#     form=Movieform(instance=m)
#     return render(request,'addmovie.html',{'form':form})

class Update(UpdateView):
    model = Movie
    template_name = 'addmovie.html'
    fields=['name','desc','year','image']
    success_url = reverse_lazy('movieapp:home')

# def delete(request,n):
#     m=Movie.objects.get(id=n)
#     m.delete()
#     return home(request)

class Delete(DeleteView):
    model=Movie
    template_name ='delete.html'
    success_url=reverse_lazy('movieapp:home')

# def addmovie(request):
#     if(request.method=='POST'):
#         form=Movieform(request.POST,request.FILES)
#         if form.is_valid():
#             form.save()
#             return home(request)
#
#     form=Movieform()
#     return render(request,'addmovie.html',{'form':form})

class AddMovie(CreateView):
    model=Movie
    template_name = 'addmovie.html'
    fields=['name','desc','year','image']
    success_url = reverse_lazy('movieapp:home')

movie/movie/templates/addmovie.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
    {{form.as_table}}
    </table>
    <input type="submit">
</form>
{% endblock %}
</body>
</html>

movie/movie/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">ONLINE MOVIE STORE</a>
    <form class="d-flex">
      <a href="{% url 'movieapp:addmovie' %}" class="btn btn-outline-success">ADD MOVIE</a>
    </form>
  </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

movie/movie/templates/delete.html
{% extends 'base.html' %}
{% load static %}
<body>
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
    {{form.as_table}}
    </table>
    <center>
    <input type="submit" value="are you sure">
    </center>
</form>
{% endblock %}
</body>
</html>

movie/movie/templates/detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <img src="{{m.image.url}}" height="300px" width="500px"><br></div>
  </div>
  <div class="col-sm-6">
  <h2>{{m.name}}<br>{{m.year}}<br></h2><br>
  <p>{{m.desc}}</p><br>
    <a href="{% url 'movieapp:update' m.id %}" class="btn btn-secondary">Update</a>
    <a href="{% url 'movieapp:delete' m.id %}" class="btn btn-secondary">Delete</a>
  </div>
</div>
{% endblock %}
</body>
</html>

movie/movie/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<div class="container-fluid">
    <div class="row">
        {% for i in m %}
        <div class="col-sm-3">
            <div class="card" style="width: 18rem;">
  <img src="{{i.image.url}}" height="300px" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.year}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">More Details</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}
</body>
</html>

movie/movie/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>